### ISSUE TITLE
Installer for popular DSP solutions

### ISSUE THREAD

**Issue by JamesYeoman** [jaakkopasanen/AutoEq#290]
**Is your feature request related to a problem? Please describe.**
As a tech enthusiast, I don't particularly mind trawling through forums to find solutions. But it was particularly painful to find a low-latency DSP for linux that is relatively easy to use, and can autostart on login. I can imagine this to be a particularly painful teething problem for people trying to get into linux, and potentially a reason for them to forego the switch altogether.

**Describe the solution you'd like**
Considering the fact that PulseEffects supports Convolver filters, and that the convolver filters are autodetected from the `irs` folder in their config folder, I've [created a gist](https://gist.github.com/JamesYeoman/4c58fa8f81738117f3b088c1ae80b533) of a bash script for a linux/pulseaudio solution to this predicament. I've noted any caveats at the top of the gist in comments.

**Describe alternatives you've considered**
I've tried T5's Parametric EQ, which was ok, but didn't have an autostart option. I've tried pulseaudio-equaliser, but `qpaeq` (the GUI for the fixed band eq) only has sliders, and doesn't show what the value of the sliders are. I've even tried https://github.com/bmc0/dsp but the startup latency from suspend is far too high that when watching a video, it starts without audio, then stops after 2 seconds so that the audio can catch up.

**Additional context**

**Comment by ADubhlaoich** [comment]
@JamesYeoman The gist you've created errors as "downloadFile" is not found; I can only assume it's a personal bash alias.

I was attempting to use it as I have been bashing my head off my desk for an hour trying to figure out how to use the PulseEffects file provided in the repo and are frustrated enough to try random things I barely comprehend.

**Comment by lierdakil** [comment]
@ADubhlaoich for the love of all that is holy, don't use that script. I've looked through, and it's just a very roundabout way of putting impulse response wave files from the results folder into `$HOME/.config/PulseEffects/irs`, while changing the extension from `wav` to `irs`. It also silently "installs" some random stuff by running arbitrary scripts downloaded from the Internet, so it's basically a gaping security hole.

Just get the impulse response file you need directly from GitHub, put it in the folder, rename to `*.irs` and select it in the convolver settings. Remember, you can search by file path in GitHub UI by clicking "Go To File" button.

**Comment by JamesYeoman** [comment]
> The gist you've created errors as "downloadFile" is not found; I can only assume it's a personal bash alias

@ADubhlaoich oops my bad. I must have renamed downloadFile to downloadZip at the last minute and forgot to sanity-check.

> It also silently "installs" some random stuff by running arbitrary scripts downloaded from the Internet

@lierdakil in what world is fetching FZF and putting it into /tmp "installing" it? I clean it up afterwards. The use of the install script in /tmp/fzf is because it fetches the platform-specific FZF binary and places it in the bin folder on the same level as the install script. It doesn't actually "install" anything. If you look, I even refrain from having my script install unzip, as I recognise that permanent installations of anything would be objected to. Even required libraries for pulseeffects like gstreamer1.0-convolver-pulseeffects aren't automatically installed. The prompt at the end tells you that you need to make sure it's installed.

If you've got any more criticism, please be constructive, rather than fearmongering

**Comment by JamesYeoman** [comment]
Also, @lierdakil I don't specifically install the irs file to `$HOME/.config/pulseeffects/irs`. I make sure I adhere to the XDG spec and have `$HOME/.config` as the fallback if `$XDG_CONFIG_HOME` isn't set.

And I don't even download FZF if it's already in path

**Comment by JamesYeoman** [comment]
I've updated the gist to add a FZF download warning and give the user an option to abort the script if they don't want it downloaded. I've also fixed a typo. I haven't got my linux environment available at the moment so I can't test, but if anyone can independently verify that the script works and everything gets correctly removed, that would be great.

**Comment by lierdakil** [comment]
@JamesYeoman, you want constructive criticism? Okay. Why are you downloading the whole repo to tmpfs just to take a couple files from it? Just get the [index](https://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/results/INDEX.md) and get URIs from there. F.ex.
```bash
curl https://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/results/INDEX.md | sed -rn 's!^- \[([^]]+)\]\(\./([^ ]+)\).*$!https://github.com/jaakkopasanen/AutoEq/blob/master/results/\2/\1 minimum phase 48000Hz.wav?raw=true!p'
```
will get you the list of URLs for impulse response files for 48000 Hz. Bear in mind, spaces need to be additionally urlencoded, but it's as simple as `sed 's/ /%20/g'`.

Also, side note, the preferred IR frequency should correspond to the audio subsystem discretization frequency, which in my experience is 48 kHz more often than not. So defaulting to 44.1 kHz seems dubious.

**Comment by JamesYeoman** [comment]
Ah, that's a lot cleaner of a solution. Thanks. I have trouble reading regex because all the symbols start to meld together after not very long, which is why I opted for the file solution. The main point of all this was a fuzzy search for a headset, in order to grab the required impulse responses.

As for the side note, it's irrelevant, as I don't _default_ to anything. I grab both the 44.1 and 48 IR files. I simply _search_ for the 44.1kHz file as it's an anchor point. I agree, I could have made it much less hacky than I did, but at no point did I say that the script was 100% ready for prime time. Just that I had something that worked.

I genuinely appreciate the feedback. When I get some free time, I'll have a look at all the potential ways to reduce the footprint of the script, starting off with your suggestion regarding the index.

@ADubhlaoich if you haven't already moved on yet, could you give my gist another go please? And let me know if /tmp gets correctly cleaned up

**Comment by lierdakil** [comment]
@JamesYeoman you still have `downloadFile` at line 89, so the script is still broken.

**Comment by JamesYeoman** [comment]
Whoops my bad, I did a find+replace this time

**Comment by JamesYeoman** [comment]
It's annoying doing on-the-fly fixes when you don't have an environment to test them in

**Comment by jaakkopasanen** [comment]
I'm sure what this issue is asking for. It's an external script for PulseEffects or something? In any case I don't have any of these solutions in the insturctions and I don't much care to have. Closing the issue.
